# Metadatos - Darwin Core

El Darwin Core (DwC) es un conjunto de estándares mantenidos por [TDWG](https://www.tdwg.org) (Biodiversity Information Standards, anteriormente conocido como The International Working Group on Taxonomic Databases).
Incluye un glosario de términos destinado a facilitar el intercambio de información sobre la diversidad biológica al proporcionar definiciones de referencia, ejemplos y comentarios. El Darwin Core se basa principalmente en taxones, su presencia en la naturaleza documentada mediante observaciones, especímenes y muestras, y la información relacionada.

El Darwin Core gira en torno a un formato de archivo estándar, el Darwin Core Archive (DwC-A). Este paquete compacto (un archivo ZIP) contiene archivos de texto interconectados y permite a los editores de datos compartir sus datos utilizando una terminología común. DwC es utilizado tanto por GBIF [GBIF](www.gbif.org) como por OBIS [OBIS](www.obis.org) para la publicación de datos.

Esta estandarización no solo simplifica el proceso de publicación de conjuntos de datos de biodiversidad, sino que también facilita que los usuarios descubran, busquen, evalúen y comparen conjuntos de datos mientras buscan respuestas a las preguntas de investigación y políticas intensivas en datos de hoy.

## Estructura de Darwin Core

Un archivo DWC-A puede contener 4 tipos de componentess. Estos archivos pueden incluir:

* eml.xml
* aricho princial (core file)
* archivos de extensión (opcional)
* meta.xml

EML significa [Ecological Metadata Language](https://en.wikipedia.org/wiki/Ecological_Metadata_Language). Este archivo contiene los metadatos del conjunto de datos en formato XML.

Los archivos principales (core) y de extensión contienen registros de datos, dispuestos uno por línea. Cada fila en el archivo de extensión o registro de extensión apunta a un solo registro en el archivo principal (core). Para cada registro principal puede haber muchos registros de extensión. A esto a veces se le llama un "esquema en estrella" ("star schema").

El archivo meta.xml describe cómo se organizan los archivos en el archivo de datos. Describe la relación entre los archivos principales (core) y de extensión y asigna nombres de columnas no estándar a términos del Darwin Core.

To publish the data as a DwC-A, we recommend to upload the core and extension files to the IPT (e.g. [IPT.biodiversity.aq](http://IPT.biodiversity.aq)). Use the IPT's built-in metadata editor to enter dataset metadata. The IPT will compile the EML on the data you provided, as well as the meta.xml.

## Tipos de archivos en Darwin Core

*  Metadatos de recursos [Resource Metadata](https://github.com/gbif/ipt/wiki/resourceMetadata) - Utilizados para describir un recurso de información sobre biodiversidad, incluyendo detalles de contacto, incluso si actualmente no se pueden compartir datos digitales (esto proporciona una forma para que los investigadores descubran recursos que aún no están disponibles en línea).
* Lista de verificación [Checklist](https://github.com/gbif/ipt/wiki/checklistData) - Utilizados para compartir listas de verificación de especies, catálogos taxonómicos y otra información sobre taxones.
* Ocurrencia [Occurrence](https://github.com/gbif/ipt/wiki/occurrenceData) - Utilizados para compartir información sobre una instancia específica de un taxón, como un espécimen u observación.
* Evento [Event](https://github.com/gbif/ipt/wiki/samplingEventData) - Utilizados para compartir información sobre los protocolos utilizados en investigaciones ecológicas.ns.


## Detalles del Darwin Core

En general, los metadatos EML acompañarán a algún archivo principal de datos en un DwC-A. Proporciona una descripción y detalles sobre el recurso.

También es posible publicar inicialmente solo sus metadatos y agregar sus datos mas adelante.

Esto permite que los investigadores descubran recursos que aún no están disponibles en línea.
Lo mejor es considerar el resumen como la sección de materiales y métodos de su artículo, pero solo para sus datos. Trate de proporcionar la mayor cantidad de detalles posible.

De hecho, si completa sus metadatos de manera exhaustiva, tendrá un primer borrador muy bueno para un artículo de datos (si eso es algo que le gustaría hacer). Solo tendrá que agregar algunos mapas, estadísticas y estará listo.

Si tiene prisa, a continuación se muestra una descripción general de los campos requeridos actualmente.

Si utiliza el IPT para crear su archivo del Darwin Core, deberá elegir un nombre corto para su conjunto de datos. Elija esto sabiamente porque no se puede cambiar. El nombre corto sirve como identificador dentro de la instalación del IPT y se utilizará como parámetro en la URL para acceder al recurso a través de Internet. Para el nombre corto, solo puede usar caracteres alfanuméricos, guiones o guiones bajos.

### Campos de metadata requeridos:

#### Metadatos básicos

##### Título
> Este será el título largo de su conjunto de datos y cómo se citará el conjunto de datos.

##### Organización de publicación
>Por favor, seleccione la organización responsable de publicar (producir, liberar, mantener) este recurso. Se utilizará como la organización de publicación del recurso al registrar este recurso en GBIF y al enviar metadatos durante el registro de DOI. También se utilizará para generar automáticamente la cita del recurso (si la generación automática está activada), así que considere la importancia de la función. Tenga en cuenta que su selección no se puede cambiar después de que el recurso haya sido registrado en GBIF o se le haya asignado un DOI.

En nuestro IPT puede elegir

* Antarctic Biodiversity Information Facility (AntaBIF) para conjuntos de datos terrestres
* SCAR - AntOBIS para conjuntos de datos marinos
* SCAR - Microbial Antarctic Resource System para conjuntos de datos microbianos

También podemos publicar en nombre de otros. Actualmente tenemos acuerdos con

* British Antarctic Survey
* Italian Antarctic National Museum (MNA, section Genua)
 

##### Tipo
>El tipo de recurso. El valor de este campo depende de la asignación principal del recurso y no es editable si ya se ha realizado la asignación del Darwin Core.

Esto puede ser

* Metadata-only - solo metadatos
* Checklist - Lista de verificación
* Occurence -Ocurrencia
* Event-Core - Evento central

##### Idioma/lenguaje de los metadatos
>El idioma en el que está escrito el documento de metadatos.

##### Idioma/lenguaje de datos
>El idioma principal en el que están escritos los datos descritos (no el documento de metadatos).

##### Frecuencia de actualización
>La frecuencia con la que se realizan cambios en el recurso después de que se haya publicado inicialmente. Por conveniencia, su valor se establecerá por defecto en el intervalo de publicación automática (si se ha activado la publicación automática), sin embargo, siempre se puede anular más tarde. Tenga en cuenta que también se puede introducir una descripción de la frecuencia de mantenimiento del recurso en la página de Metadatos adicionales.

##### licensia de datos
>La licencia que se aplica a un conjunto de datos proporciona una forma estandarizada de definir los usos adecuados de su trabajo. GBIF alienta a los editores a adoptar la licencia menos restrictiva posible entre tres opciones legibles por máquina (CC0 1.0, CC-BY 4.0 o CC-BY-NC 4.0) para fomentar el uso y la aplicación más amplios de los datos. Obtenga más información aquí. Si no puede elegir una de las tres opciones y su conjunto de datos contiene datos de ocurrencia, no podrá registrar su conjunto de datos en GBIF ni hacerlo globalmente descubrible a través de GBIF.org. Si se siente incapaz de seleccionar una de las tres opciones, comuníquese con la Secretaría de GBIF en participation@gbif.org.


##### Descripción
>Una breve descripción del recurso que se está documentando, dividida en párrafos.

Piense en esto como un resumen para un artículo de datos

##### Contacto(s) del recurso
##### Creador(es) del recurso
##### Proveedor(es) de metadatos
* Apellido
* Cargo
* Organisación
	
#### Cobertura geográfica
##### Descripción



### Generación automatica de citas/referencias

Creator 1 R, Creator 2 R, Creator 3 R (2019): How to create a metadata record. v1. Publishing organisation. Dataset/Type. https://ipt.biodiversity.aq/resource?r=shortname&amp;v=1.0

#### Ejemplo

Griffiths H J, Linse K, Crame J (2017): SOMBASE – Southern Ocean mollusc database: a tool for biogeographic analysis in diversity and evolution. v1.6. British Antarctic Survey. Dataset/Occurrence. https://ipt.biodiversity.aq/resource?r=sombase_southern_ocean_mollusc_database&amp;v=1.6

