# Otros recursos en `R` relacionados al Océano del Sur y la Antártida

## Datos de dieta: `sohungry`

La librería [`sohungry`](https://github.com/SCAR/sohungry) te da acceso a la base de datos [Southern Ocean Diet and Energetics de SCAR](http://data.aad.gov.au/trophic/), así como algunas herramientas que te permiten trabajar con estos datos. La base datos incluye datos sobre dieta y flujos energéticos de estudios convencionales (por ej., contenidos de estómagos) y modernos (por ej., métodos moleculares), isótopos estables, ácidos grasos, y contenido energético. Este es un producto de la comunidad SCAR de acceso abierto y la cual está abierta a nuevos contribuyentes de datos.

Mira la [viñeta de la librería `sohungry`](https://scar.github.io/sohungry/articles/sohungry.html) para más información.

## Ecuaciones alométricas: `solong`

La librería [`solong`](https://github.com/SCAR/solong) incluye ecuaciones alométricas relacionadas a organismos del Océano del Sur. Estas ecuaciones son parte de la base de datos Southern Ocean Diet and Energetics de SCAR. Para más información, presiona [aquí](https://scar.github.io/solong/).
